apiVersion: v1
kind: Service
metadata:
  name: oai-oran
  labels:
    {{- include "oai-oran.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: e2
      port: {{ .Values.config.e2Port}}
      targetPort: {{ .Values.config.e2Port}}
      protocol: SCTP
    - name: prometheus
      port: 9090
      targetPort: 9090
      protocol: TCP  
  selector:
    {{- include "oai-oran.selectorLabels" . | nindent 4 }}
